import Head from "next/head";
import Link from 'next/link';

const SEO = ({ pageTitle,font }) => (
  <>
    <Head>
      <title>
        {pageTitle && `${pageTitle} || Gardomia - Landscape and Gardening React Next js Template}`}
      </title>
      <meta httpEquiv="x-ua-compatible" content="ie=edge" />
      <meta name="description" content="Generated by create next app" />
      <meta name="robots" content="noindex, follow" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no"
      />
      
      {font && <Link href={font} rel="stylesheet" />}
      <Link rel="icon" href="/favicon.png" />
    </Head>
  </>
);

export default SEO;